spring.datasource.url=${DATABASE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:hasilpanen}}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:${SPRING_DATASOURCE_USERNAME:postgres}}
spring.datasource.password=${DB_PASSWORD:${SPRING_DATASOURCE_PASSWORD:postgres}}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

storage.provider=${STORAGE_PROVIDER:cloudinary}
